/* Copyright Statement:
*
* This software/firmware and related documentation ("MediaTek Software") are
* protected under relevant copyright laws. The information contained herein
* is confidential and proprietary to MediaTek Inc. and/or its licensors.
* Without the prior written permission of MediaTek inc. and/or its licensors,
* any reproduction, modification, use or disclosure of MediaTek Software,
* and information contained herein, in whole or in part, shall be strictly prohibited.
*/
/* MediaTek Inc. (C) 2015. All rights reserved.
*
* BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
* THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
* RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
* AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
* NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
* SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
* SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
* THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
* THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
* CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
* SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
* STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
* CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
* AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
* OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
* MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*/

#ifndef _DDP_REG_SPLIT_H_
#define _DDP_REG_SPLIT_H_

#include "hw/DISP_SPLIT_c_header.h"

/* for split driver */
#define DISP_REG_SPLIT_ENABLE				DISP_SPLIT_EN
#define DISP_REG_SPLIT_SW_RESET				DISP_SPLIT_RESET
#define DISP_REG_SPLIT_INTEN 				DISP_SPLIT_INTEN
#define DISP_REG_SPLIT_INTSTA				DISP_SPLIT_INTSTA
#define DISP_REG_SPLIT_HSIZE                DISP_SPLIT_HSIZE
#define DISP_REG_SPLIT_VSIZE                DISP_SPLIT_VSIZE          
#define DISP_REG_SPLIT_SHADOW_CTRL			DISP_SPLIT_SHADOW_CTRL

/* for debug */
#define DISP_REG_SPLIT_STATUS 				DISP_SPLIT_STATUS
#define DISP_REG_SPLIT_INPUT_COUNT		 	DISP_SPLIT_INPUT_COUNT
#define DISP_REG_SPLIT_LEFT_OUTPUT_COUNT 	DISP_SPLIT_LEFT_OUTPUT_COUNT
#define DISP_REG_SPLIT_RIGHT_OUTPUT_COUNT	DISP_SPLIT_RIGHT_OUTPUT_COUNT
#define DISP_REG_SPLIT_INFO_A               DISP_SPLIT_INFO_A
#define DISP_REG_SPLIT_INFO_B               DISP_SPLIT_INFO_B
#define DISP_REG_SPLIT_INFO_C               DISP_SPLIT_INFO_C

/* field */
#define ENABLE_FLD_SPLIT_EN					EN_FLD_SPLIT_EN
#define W_RESET_FLD_SPLIT_SW_RST			RESET_FLD_SPLIT_RESET
#define FLD_BYPASS_SHADOW					SHADOW_CTRL_FLD_BYPASS_SHADOW
#define FLD_READ_WRK_REG					SHADOW_CTRL_FLD_READ_WRK_REG



#define REG_HSIZE_FLD_HSIZE_L				HSIZE_FLD_HSIZE_L
#define REG_HSIZE_FLD_HSIZE_R				HSIZE_FLD_HSIZE_R
#define REG_VSIZE_FLD_VSIZE					VSIZE_FLD_VSIZE


#endif
