#
LOCAL_DIR := $(GET_LOCAL_DIR)
TARGET := k61v1_hdp_ref
MODULES += app/mt_boot \
           dev/lcm
MTK_EMMC_SUPPORT = yes
MTK_MMC_COMBO_DRV = yes
MTK_SMI_SUPPORT = yes
MTK_KERNEL_POWER_OFF_CHARGING = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
DEFINES += MTK_GPT_SCHEME_SUPPORT
MTK_CHARGER_NEW_ARCH := yes
MTK_PUMP_EXPRESS_PLUS_SUPPORT := no
MTK_BQ25601_SUPPORT := yes
DEFINES += MTK_BQ25601_SUPPORT
MTK_CHARGER_INTERFACE := yes
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM="nt36672ah_hdp_dsi_vdo_tcl_csot"
DEFINES += MTK_ROUND_CORNER_SUPPORT
#nt35595_fhd_dsi_cmd_truly_nt50358 = yes
#FASTBOOT_USE_G_ORIGINAL_PROTOCOL = yes
MTK_SECURITY_SW_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes
SPM_FW_USE_PARTITION = yes
BOOT_LOGO := hdplus1500
#DEFINES += MTK_LCM_PHYSICAL_ROTATION_HW
DEBUG := 2
#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
CUSTOM_LK_USB_UNIQUE_SERIAL=no
MTK_TINYSYS_SCP_SUPPORT = yes
MTK_TINYSYS_SSPM_SUPPORT = yes
#DEFINES += NO_POWER_OFF=y
#DEFINES += FPGA_BOOT_FROM_LK=y
MTK_PROTOCOL1_RAT_CONFIG = Lf/Lt/W/G
MTK_GOOGLE_TRUSTY_SUPPORT = no
MTK_EFUSE_WRITER_SUPPORT = no
MTK_SMC_ID_MGMT = yes
DEVELOP_STAGE = SB
MTK_MT22_MODE :=H2
MTK_MINIMUM_SCP_DRAM_SIZE = yes
ifneq ($(filter user userdebug, $(TARGET_BUILD_VARIANT)),)
MTK_DYNAMIC_CCB_BUFFER_GEAR_ID = 3
else
MTK_DYNAMIC_CCB_BUFFER_GEAR_ID =
endif
MTK_DIS_ATF_RAM_DUMP = yes
