/* Copyright Statement:
*
* This software/firmware and related documentation ("MediaTek Software") are
* protected under relevant copyright laws. The information contained herein
* is confidential and proprietary to MediaTek Inc. and/or its licensors.
* Without the prior written permission of MediaTek inc. and/or its licensors,
* any reproduction, modification, use or disclosure of MediaTek Software,
* and information contained herein, in whole or in part, shall be strictly prohibited.
*/
/* MediaTek Inc. (C) 2008. All rights reserved.
*
* BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
* THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
* RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
* AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
* NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
* SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
* SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
* THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
* THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
* CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
* SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
* STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
* CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
* AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
* OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
* MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*/
#ifndef __DISP_ASSERT_LAYER_H__
#define __DISP_ASSERT_LAYER_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
   DAL_STATUS_OK                = 0,

   DAL_STATUS_NOT_READY         = -1,
   DAL_STATUS_INVALID_ARGUMENT  = -2,
   DAL_STATUS_LOCK_FAIL         = -3,
   DAL_STATUS_LCD_IN_SUSPEND    = -4,
   DAL_STATUS_FATAL_ERROR       = -10,
} DAL_STATUS;


typedef enum
{
   DAL_COLOR_BLACK     = 0x000000,
   DAL_COLOR_WHITE     = 0xFFFFFF,
   DAL_COLOR_RED       = 0xFF0000,
   DAL_COLOR_GREEN     = 0x00FF00,
   DAL_COLOR_BLUE      = 0x0000FF,
   DAL_COLOR_TURQUOISE = (DAL_COLOR_GREEN | DAL_COLOR_BLUE),
   DAL_COLOR_YELLOW    = (DAL_COLOR_RED | DAL_COLOR_GREEN),
   DAL_COLOR_PINK      = (DAL_COLOR_RED | DAL_COLOR_BLUE),
} DAL_COLOR;


/* Display Assertion Layer API */

unsigned int DAL_GetLayerSize(void);

DAL_STATUS DAL_Init(unsigned int layerVA, unsigned int layerPA);
DAL_STATUS DAL_SetColor(unsigned int fgColor, unsigned int bgColor);
DAL_STATUS DAL_Clean(void);
DAL_STATUS DAL_Printf(const char *fmt, ...);
DAL_STATUS DAL_OnDispPowerOn(void);
DAL_STATUS DAL_LowMemoryOn(void);
DAL_STATUS DAL_LowMemoryOff(void);
#ifdef __cplusplus
}
#endif

#endif // __DISP_ASSERT_LAYER_H__
